apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: map-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: map-service
    app.kubernetes.io/part-of: dc-metro-map
  name: map-service
  namespace: user1-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: map-service
    weight: 100
status: {}
